title: Striver 450
description: My revision notes for Striver's DSA sheet. Every solution in C++.
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
color_scheme: vibrant
search_enabled: true
back_to_top: true
back_to_top_text: "Back to top"
aux_links:
  "GitHub": "https://github.com/visheshkodwani/Striver-450"
total_problems: 450
