title: Striver 450
description: My notes on Striver's DSA sheet, in C++.
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
color_scheme: vibrant
search_enabled: true
back_to_top: true
back_to_top_text: "Back to top"
aux_links:
  "GitHub": "https://github.com/visheshkodwani/Striver-450"
